// src/lib/components/sermons/SermonBrowser.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Sermon } from '$lib/types/sermon';
  import { sermonService, type MediaType } from '$lib/services/sermonService';
  import { ChevronDown, ChevronUp } from 'lucide-svelte';

  export let type: MediaType = 'sermons';
  
  let loading = true;
  let error: string | null = null;
  let organizedSermons: Record<string, Record<string, Sermon[]>> = {};
  let expandedYears: Set<string> = new Set();
  let expandedMonths: Set<string> = new Set();
  let selectedSermon: Sermon | null = null;
  let videoLoading = true;

  function toggleYear(year: string) {
    if (expandedYears.has(year)) {
      expandedYears.delete(year);
    } else {
      expandedYears.add(year);
    }
    expandedYears = expandedYears; // Trigger reactivity
  }

  function toggleMonth(monthKey: string) {
    if (expandedMonths.has(monthKey)) {
      expandedMonths.delete(monthKey);
    } else {
      expandedMonths.add(monthKey);
    }
    expandedMonths = expandedMonths; // Trigger reactivity
  }

  function selectSermon(sermon: Sermon) {
    selectedSermon = sermon;
    videoLoading = true;
  }

  function handleVideoLoad() {
    videoLoading = false;
  }

  function getJellyfinUrl(path: string) {
    const JELLYFIN_URL = 'https://jellyfin.rockvilletollandsda.church';
    const JELLYFIN_API_KEY = import.meta.env.VITE_JELLYFIN_API_KEY;
    
    if (path.startsWith('details?id=')) {
      const itemId = path.replace('details?id=', '');
      return `${JELLYFIN_URL}/Videos/${itemId}/stream.mp4?static=true&api_key=${JELLYFIN_API_KEY}`;
    }
    return `${JELLYFIN_URL}/${path}`;
  }

  async function loadSermons() {
    try {
      loading = true;
      error = null;
      sermonService.setType(type);
      organizedSermons = await sermonService.getSermonsByYearAndMonth();
      
      // Expand the most recent year by default
      const years = Object.keys(organizedSermons);
      if (years.length > 0) {
        expandedYears.add(years[0]);
        const months = Object.keys(organizedSermons[years[0]]);
        if (months.length > 0) {
          expandedMonths.add(`${years[0]}-${months[0]}`);
          const sermons = organizedSermons[years[0]][months[0]];
          if (sermons.length > 0) {
            selectedSermon = sermons[0];
          }
        }
      }
    } catch (err) {
      console.error('Error loading sermons:', err);
      error = 'Failed to load sermons. Please try again later.';
    } finally {
      loading = false;
    }
  }

  $: {
    type; // Watch for type changes
    loadSermons();
  }
</script>

<div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
  <!-- Sermon Browser -->
  <div class="lg:col-span-1 bg-white rounded-2xl shadow-lg overflow-hidden">
    <div class="p-4 border-b border-gray-200">
      <h3 class="text-lg font-semibold text-gray-900">Browse {type === 'sermons' ? 'Sermons' : 'Livestreams'}</h3>
    </div>
    
    {#if loading}
      <div class="flex items-center justify-center p-8">
        <div class="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-blue-500"></div>
      </div>
    {:else if error}
      <div class="p-4 text-red-600">{error}</div>
    {:else}
      <div class="divide-y divide-gray-200">
        {#each Object.entries(organizedSermons) as [year, months]}
          <div class="overflow-hidden">
            <button
              class="w-full px-4 py-3 flex items-center justify-between hover:bg-gray-50 transition-colors"
              on:click={() => toggleYear(year)}
            >
              <span class="font-medium text-gray-900">{year}</span>
              {#if expandedYears.has(year)}
                <ChevronUp class="h-5 w-5 text-gray-500" />
              {:else}
                <ChevronDown class="h-5 w-5 text-gray-500" />
              {/if}
            </button>
            
            {#if expandedYears.has(year)}
              <div class="bg-gray-50">
                {#each Object.entries(months) as [month, sermons]}
                  <div class="border-t border-gray-200">
                    <button
                      class="w-full px-6 py-2 flex items-center justify-between hover:bg-gray-100 transition-colors"
                      on:click={() => toggleMonth(`${year}-${month}`)}
                    >
                      <span class="text-sm font-medium text-gray-700">{month}</span>
                      {#if expandedMonths.has(`${year}-${month}`)}
                        <ChevronUp class="h-4 w-4 text-gray-500" />
                      {:else}
                        <ChevronDown class="h-4 w-4 text-gray-500" />
                      {/if}
                    </button>
                    
                    {#if expandedMonths.has(`${year}-${month}`)}
                      <div class="border-t border-gray-200">
                        {#each sermons as sermon}
                          <button
                            class="w-full px-8 py-2 text-left hover:bg-gray-100 transition-colors {selectedSermon?.id === sermon.id ? 'bg-blue-50' : ''}"
                            on:click={() => selectSermon(sermon)}
                          >
                            <h4 class="text-sm font-medium text-gray-900 truncate">{sermon.title}</h4>
                            <p class="text-xs text-gray-500 mt-1">
                              {new Date(sermon.date).toLocaleDateString('en-US', {
                                month: 'long',
                                day: 'numeric',
                                year: 'numeric'
                              })}
                            </p>
                          </button>
                        {/each}
                      </div>
                    {/if}
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </div>

  <!-- Video Player -->
  <div class="lg:col-span-2">
    {#if selectedSermon}
      <div class="bg-white rounded-2xl shadow-lg overflow-hidden">
        <div class="relative aspect-[16/9]">
          {#if videoLoading}
            <div class="absolute inset-0 bg-gray-100 flex items-center justify-center">
              <div class="flex flex-col items-center">
                <div class="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500"></div>
                <p class="text-gray-600 mt-4">Fetching {type === 'sermons' ? 'Sermon' : 'Video'}...</p>
              </div>
            </div>
          {/if}
          <video
            src={getJellyfinUrl(`details?id=${selectedSermon.jellyfinId}`)}
            class="absolute inset-0 w-full h-full {videoLoading ? 'opacity-0' : 'opacity-100'} transition-opacity duration-300"
            controls
            preload="metadata"
            on:loadeddata={handleVideoLoad}
          >
            <track kind="captions" />
          </video>
        </div>
        <div class="p-6">
          <h3 class="text-xl font-bold text-gray-900 mb-2">{selectedSermon.title}</h3>
          <p class="text-gray-600">
            Speaker: {selectedSermon.speaker}<br />
            Date: {new Date(selectedSermon.date).toLocaleDateString('en-US', { 
              weekday: 'long',
              year: 'numeric',
              month: 'long',
              day: 'numeric'
            })}
            {#if selectedSermon.seriesName}
              <br />Series: {selectedSermon.seriesName}
            {/if}
          </p>
          {#if selectedSermon.description}
            <p class="mt-4 text-gray-600">{selectedSermon.description}</p>
          {/if}
        </div>
      </div>
    {:else}
      <div class="bg-white rounded-2xl shadow-lg p-8 text-center">
        <p class="text-gray-600">Select a {type === 'sermons' ? 'sermon' : 'video'} to watch</p>
      </div>
    {/if}
  </div>
</div>

// src/components/sermons/SermonBrowser.tsx
'use client';

import { useState, useEffect } from 'react';
import { sermonService, type Sermon } from '@/services/SermonService';

interface SermonBrowserProps {
  onSermonSelect?: (sermon: Sermon) => void;
}

export default function SermonBrowser({ onSermonSelect }: SermonBrowserProps) {
  const [years, setYears] = useState<string[]>([]);
  const [months, setMonths] = useState<string[]>([]);
  const [sermons, setSermons] = useState<Sermon[]>([]);
  const [selectedYear, setSelectedYear] = useState<string | null>(null);
  const [selectedMonth, setSelectedMonth] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Format month from "01-January" to "January"
  const formatMonth = (month: string) => {
    return month.split('-')[1] || month;
  };

  // Load initial years
  useEffect(() => {
    const loadYears = async () => {
      try {
        const years = await sermonService.fetchYears();
        setYears(years);
        if (years.length > 0) {
          setSelectedYear(years[0]);
        }
      } catch (err) {
        setError('Failed to load years');
        console.error('Error loading years:', err);
      } finally {
        setIsLoading(false);
      }
    };

    loadYears();
  }, []);

  // Load months when year is selected
  useEffect(() => {
    if (!selectedYear) return;

    const loadMonths = async () => {
      try {
        setIsLoading(true);
        const months = await sermonService.fetchMonths(selectedYear);
        setMonths(months);
        if (months.length > 0) {
          setSelectedMonth(months[0]);
        }
      } catch (err) {
        setError('Failed to load months');
        console.error('Error loading months:', err);
      } finally {
        setIsLoading(false);
      }
    };

    loadMonths();
  }, [selectedYear]);

  // Load sermons when month is selected
  useEffect(() => {
    if (!selectedYear || !selectedMonth) return;

    const loadSermons = async () => {
      try {
        setIsLoading(true);
        const sermons = await sermonService.fetchSermons(selectedYear, selectedMonth);
        setSermons(sermons);
      } catch (err) {
        setError('Failed to load sermons');
        console.error('Error loading sermons:', err);
      } finally {
        setIsLoading(false);
      }
    };

    loadSermons();
  }, [selectedYear, selectedMonth]);

  if (isLoading && years.length === 0) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-8">
        <div className="text-red-500 text-5xl mb-4">⚠️</div>
        <h3 className="text-xl font-bold mb-2">Error loading sermons</h3>
        <p className="text-gray-600">{error}</p>
        <button
          onClick={() => window.location.reload()}
          className="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
        >
          Try Again
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Year Selection */}
      <div className="space-y-2">
        <h3 className="text-sm font-medium text-gray-500">Select Year</h3>
        <div className="flex gap-2 overflow-x-auto pb-2">
          {years.map((year) => (
            <button
              key={year}
              onClick={() => setSelectedYear(year)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
                selectedYear === year
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              {year}
            </button>
          ))}
        </div>
      </div>

      {/* Month Selection */}
      {selectedYear && months.length > 0 && (
        <div className="space-y-2">
          <h3 className="text-sm font-medium text-gray-500">Select Month</h3>
          <div className="flex gap-2 overflow-x-auto pb-2">
            {months.map((month) => (
              <button
                key={month}
                onClick={() => setSelectedMonth(month)}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
                  selectedMonth === month
                    ? 'bg-blue-500 text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {formatMonth(month)}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Sermons List */}
      <div className="space-y-4">
        {sermons.length === 0 && selectedMonth ? (
          <div className="text-center py-8">
            <div className="text-4xl mb-4">🎥</div>
            <h3 className="text-xl font-bold mb-2">No Sermons Available</h3>
            <p className="text-gray-600">
              There are no recorded sermons for this month. Try selecting a different month.
            </p>
          </div>
        ) : (
          sermons.map((sermon) => (
            <div
              key={sermon.id}
              className="bg-white rounded-lg shadow-lg overflow-hidden cursor-pointer hover:shadow-xl transition-shadow"
              onClick={() => onSermonSelect?.(sermon)}
            >
              <div className="p-6">
                <h3 className="text-xl font-bold mb-2">{sermon.title}</h3>
                <p className="text-gray-600 mb-4">
                  Speaker: {sermon.speaker}<br />
                  Date: {sermon.date}
                </p>
                {sermon.description && (
                  <p className="text-gray-700 mb-4">{sermon.description}</p>
                )}
                {sermon.video_url && (
                  <div className="aspect-w-16 aspect-h-9">
                    <video 
                      className="w-full rounded-lg"
                      controls
                      preload="metadata"
                    >
                      <source src={`https://api.rockvilletollandsda.church${sermon.video_url}`} type="video/mp4" />
                      Your browser does not support the video tag.
                    </video>
                  </div>
                )}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
